version: "2"

run:
  timeout: 5m

formatters:
  enable:
    - gofmt

linters:
  default: none
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - misspell
  exclusions:
    paths:
      - "zz_generated.*"
